# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_messages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='created_date_unix',
            field=models.CharField(default=1, max_length=40),
            preserve_default=False,
        ),
    ]
